name: Actualizar agenda deportiva

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update-agenda:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Firebase Admin
        run: npm install firebase-admin

      - name: Actualizar agenda
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/update-agenda.js
